apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  namespace: nirmata
  labels:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: delete-items
        image: nirmata/kubectl:1.29.4
        command: ["sh", "-c"]
        args:
        - |
          set -e
          
          # Fetch the ConfigMap and extract items data
          items=$(kubectl get configmap items-created -n nirmata -o json | jq -r '.data | to_entries[] | "\(.key) \(.value)"')
          
          # Iterate through the items and delete them
          echo "$items" | while read -r item; do
            kubectl delete $kind $name -n nirmata || true
          done
          
          # Delete the ConfigMap itself
          kubectl delete configmap items-created -n nirmata || true
