apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  namespace: nirmata
  labels:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: nirmata-cluster-registrator
      containers:
      - name: delete-items
        image: nirmata/kubectl:1.29.4
        command: ["sh", "-c"]
        args:
        - |
          set -e
          
          # Fetch the ConfigMap and extract items data
          items=$(kubectl get configmap items-created -n nirmata -o json | jq -r '.data | to_entries[] | "\(.key) \(.value)"')
          
          # Iterate through the items and delete them
          echo "$items" | while read -r line; do
            kind=$(echo $line | awk '{print $1}')
            names=$(echo $line | awk '{print $2}')
            
            IFS=',' read -r -a nameArray <<< "$names"
            for name in "${nameArray[@]}"; do
              kubectl delete $kind $name -n nirmata || true
            done
          done
          
          # Delete the ConfigMap itself
          kubectl delete configmap items-created -n nirmata || true
