apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  namespace: nirmata
  labels:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: delete-items
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          #!/bin/sh
          set -e
          configmap=$(kubectl get configmap items-created-configmap -n nirmata -o json)
          
          # Extract the items data
          items=$(echo $configmap | jq -r '.data | to_entries[] | "\(.key) \(.value)"')
          echo "$items" | while read -r item; do

            # Delete the item
            kubectl delete $kind $name -n nirmata || true
          done
          kubectl delete configmap items-created-configmap -n nirmata || true
          
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: items-created-configmap
