---
{{- if .Values.createNs }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
  labels: {{ include "nirmata-cluster-registrator-chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nirmata:cluster-registrator
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
{{- if or (eq .Values.controllerPerms "read-write-ndp") (eq .Values.controllerPerms "admin") (eq .Values.controllerPerms "read-write")  }}
{{ toYaml .Values.privilegePerms | indent 6 }}
{{- end }}
      - create
  {{- if eq .Values.controllerPerms "read-write-ndp" }}
  - apiGroups:
      - ""
    resources:
      - bindings
      - configmaps
      - endpoints
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - persistentvolumes
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - resourcequotas
      - serviceaccounts
      - services
      - services/status
    verbs:
      - "*"
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservice
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
    verbs:
      - "*"
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - "*"
  - apiGroups:
      - authorization.k8s.io
    resources:
      - localsubjectaccessreviews
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - verticalpodautoscalers
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
    verbs:
      - "*"
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - "*"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - "*"
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - flowschemas
      - prioritylevelconfigurations
    verbs:
      - "*"
  - apiGroups:
      - kyverno.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
      - ingresses
      - ingresses/status
      - networkpolicies
    verbs:
      - "*"
  - apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/status
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - "*"
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - "*"
  - apiGroups:
      - security.nirmata.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
      - volumesnapshotcontents
      - volumesnapshots
    verbs:
      - "*"
  {{- end }}
  {{- if eq .Values.controllerPerms "admin" }}
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  {{- end }}
  {{- if eq .Values.controllerPerms "read-write" }}
  - apiGroups:
      - kyverno.io
    resources:
      - clusterpolicies
      - policies
      - policyexceptions
      - clustercleanuppolicies
      - cleanuppolicies
    verbs:
      - '*'
  {{- end }}
  - apiGroups:
      - security.nirmata.io
      - operator.kyverno.io
      - kyverno.io
    resources:
      - policies
      - policies/status
      - clusterpolicies
      - clusterpolicies/status
      - policyexceptions
      - cleanuppolicies
      - clustercleanuppolicies
      - generaterequests
      - generaterequests/status
      - reportchangerequests
      - reportchangerequests/status
      - clusterreportchangerequests
      - clusterreportchangerequests/status
      - kyvernooperators/status
      - kyvernooperators
      - imagekeys
      - imagekeys/status
      - imagekeys/finalizers
      - kyvernoes
      - kyvernoes/status
      - kyvernoconfigs
      - kyvernoconfigs/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nirmata:cluster-registrator-nirmata-readonly
rules:
- apiGroups:
  - kyverno.io
  - operator.kyverno.io
  - security.nirmata.io
  resources:
  - policies
  - policies/status
  - clusterpolicies
  - clusterpolicies/status
  - policyexceptions
  - cleanuppolicies
  - clustercleanuppolicies
  - generaterequests
  - generaterequests/status
  - reportchangerequests
  - reportchangerequests/status
  - clusterreportchangerequests
  - clusterreportchangerequests/status
  - kyvernooperators/status
  - kyvernooperators
  - imagekeys
  - imagekeys/status
  - imagekeys/finalizers
  - kyvernoes
  - kyvernoes/status
  - kyvernoconfigs
  - kyvernoconfigs/status
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - wgpolicyk8s.io/v1alpha1
  - wgpolicyk8s.io/v1alpha2
  resources:
  - policyreports
  - policyreports/status
  - clusterpolicyreports
  - clusterpolicyreports/status
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  - pods
  - pods/log
  - namespaces
  - secrets
  - configmaps
  - resourcequotas
  - limitranges
  - deployments
  - services
  - serviceaccounts
  - componentstatuses
  - endpoints
  - persistentvolumes
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nirmata:cluster-registrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nirmata:cluster-registrator
subjects:
- kind: ServiceAccount
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nirmata:cluster-registrator-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nirmata:cluster-registrator-nirmata-readonly
subjects:
- kind: ServiceAccount
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nirmata:cluster-registrator-nirmata-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nirmata:cluster-registrator-ns-admin
  namespace: nirmata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
  labels: {{ include "nirmata-cluster-registrator-chart.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: cluster-registrator
        image: ghcr.io/nirmata/cluster-registrator:{{ .Values.imageTag }}
        args:
        - "--cluster-name"
        - "{{ .Values.cluster.name }}"
        {{- if .Values.apiTokenSecret }}
        - "--token-secret"
        - "{{ .Values.apiTokenSecret }}"
        {{- end }}
        env:
        - name: CLUSTER_NAME
          value: "{{ .Values.cluster.name }}"
        - name: NIRMATA_TOKEN
          value: "{{ .Values.apiToken }}"
        - name: NIRMATA_URL
          value: "{{ .Values.nirmataURL }}"
        - name: NIRMATA_CLUSTER_TYPE
          value: "{{ .Values.cluster.type }}"
        - name: HTTP_PROXY
          value: "{{ .Values.proxy.httpProxy }}"
        - name: HTTPS_PROXY
          value: "{{ .Values.proxy.httpsProxy }}"
        - name: NO_PROXY
          value: "{{ .Values.proxy.noProxy }}"
        - name: TLS_CERT
          value: "{{ .Values.tlsCert }}"
        - name: APIKEY_SECRET_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: READ_ONLY
          value: "{{ .Values.kubeController.isReadOnly }}"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: "RuntimeDefault"
      serviceAccountName: nirmata-cluster-registrator
      restartPolicy: Never
  backoffLimit: 0
---
{{- if not .Values.createNs }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: delete-resources
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "clusterroles"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: delete-resources-binding
subjects:
- kind: ServiceAccount
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: delete-resources
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
