# # Default values for nirmata-kube-controller.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

nirmataURL: "wss://nirmata.io/tunnels"

# cluster name is required
cluster:
  name: ""
  type: "default-policy-manager-type"

# Use either apiToken or apiTokenSecret to specify the api token in NPM

# to use the apiTokenSecret, please create a secret with key 'apiKey'
# here's the example
# apiVersion: v1
# kind: Secret
# metadata:
#   name: nirmata-api-token
#   namespace: nirmata
# data:
#   apiKey: "{base64 encoded api token}"

# apiTokenSecret: "nirmata-api-token"

# to use apiToken, please specify the token directly, no base64 encode needed
# apiToken: ""

proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""

imageRegistry: "ghcr.io/nirmata/nirmata-kube-controller"
imageTag: "v3.10.6"
