{{ range $name, $secret := .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ template "kyverno.namespace" $ }}
  labels:
    {{- include "kyverno.config.labels" $ | nindent 4 }}
{{- $commonAnnotations := include "kyverno.annotations.common" . | nindent 4 }}
{{- if $commonAnnotations }}
  annotations:
{{ $commonAnnotations }}
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "kyverno.config.imagePullSecret" $secret }}
{{ end }}
