{{- if and (eq .Values.kyverno.rbac.create true) (contains "v1.9" .Values.kyverno.image.tag) (eq (include "enterprise-kyverno.createKyvernoNamespace" .) "true") }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- include "kyverno19.labels" . | nindent 4 }}
  name: {{ include "kyverno.namespace" . }}
{{- end }}
