{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: {{ .Values.namespace.name }}
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kyverno-aws-adapter
    app.kubernetes.io/part-of: kyverno-aws-adapter
  name: {{ .Values.namespace.name }}
{{- end }}
