apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  {{- if .Values.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
  {{- end }}
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kyverno-aws-adapter
    app.kubernetes.io/part-of: kyverno-aws-adapter
  name: kyverno-aws-adapter-sa
  namespace: {{ .Values.namespace.name }}
