apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.kubeBench.namespace }}
  name: {{ include "kube-bench.fullname" . }}
  labels:
    {{- include "kube-bench.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    {{ include "kube-bench.jobTemplate" . | nindent 4 }}
